const CLUSTER_MAP = new Map([
    ["hel", "eu-east"],
    ["sto", "eu-east"],
    ["view", "eu-east"],
    ["vie", "eu-east"],
    ["waw", "eu-east"],
    ["ams", "eu-west"],
    ["fra", "eu-west"],
    ["lhr", "eu-west"],
    ["lux", "eu-west"],
    ["mad", "eu-west"],
    ["par", "eu-west"],
    ["auw2", "na-west"],
    ["eat", "na-west"],
    ["dfw", "na-west"],
    ["lax", "na-west"],
    ["sea", "na-west"],
    ["atl", "na-east"],
    ["iad", "na-east"],
    ["okc", "na-east"],
    ["ord", "na-east"],
    ["eze", "sa"],
    ["gru", "sa"],
    ["lim", "sa"],
    ["scl", "sa"],
    ["jnb", "af"],
    ["bom", "as"],
    ["can", "as"],
    ["dxb", "as"],
    ["hkg", "as"],
    ["maa", "as"],
    ["man", "as"],
    ["pwg", "as"],
    ["pwj", "as"],
    ["pwu", "as"],
    ["pww", "as"],
    ["pwz", "as"],
    ["seo", "as"],
    ["sgp", "as"],
    ["sha", "as"],
    ["shb", "as"],
    ["tsn", "as"],
    ["tyo", "as"],
    ["ctu", "as"],
    ["syd", "oc"],
    ["", "other"],
]);

module.exports = {
    CLUSTER_MAP,
};
